demo/jstree-demo/src/Entity/File.php
<?php

namespace App\Entity;

use ApiPlatform\Elasticsearch\Filter\OrderFilter;
use App\Repository\FileRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Survos\Tree\Traits\TreeTrait;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Serializer\Filter\PropertyFilter;

#[ApiResource(
    normalizationContext: ['groups' => ['Default','jstree','minimum', 'marking','transitions', 'rp']],
    denormalizationContext: ['groups' => ["Default", "minimum", "browse"]],
)]
#[ApiFilter(OrderFilter::class, properties: ['marking', 'org', 'shortName', 'fullName'], arguments: ['orderParameterName' => 'order'])]
#[ApiFilter(SearchFilter::class, properties: ['id'=> 'exact', 'name' => 'partial', 'isDir' => 'exact'])]
#[Gedmo\Tree(type: "nested")]
#[ORM\Entity(repositoryClass: FileRepository::class)]
class File implements \Stringable
{
    use TreeTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Groups(['minimum','search','jstree'])]
    private $id;
    #[ORM\Column(type: 'string', length: 255)]
    #[Groups(['minimum','search','jstree'])]
    private $name;
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $path;
    #[ORM\Column(type: 'boolean')]
    #[Groups(['minimum','search','jstree'])]
    private $isDir;
//    #[Gedmo\TreeLeft]
//    #[ORM\Column(type: 'integer')]
//    private $lft;
//    #[Gedmo\TreeLevel]
//    #[ORM\Column(type: 'integer')]
//    private $lvl;
//    #[Gedmo\TreeRight]
//    #[ORM\Column(type: 'integer')]
//    private $rgt;
//    #[Gedmo\TreeRoot]
//    #[ORM\ManyToOne(targetEntity: 'File')]
//    #[ORM\JoinColumn(referencedColumnName: 'id', onDelete: 'CASCADE')]
//    private $root;
//    #[Gedmo\TreeParent]
//    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'children')]
//    #[ORM\JoinColumn(referencedColumnName: 'id', onDelete: 'CASCADE')]
//    private $parent;
//    #[ORM\OneToMany(targetEntity: self::class, mappedBy: 'parent')]
//    #[ORM\OrderBy(['left' => 'ASC'])]
//    private $children;
    public function __construct()
    {
        $this->children = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    public function getPath(): ?string
    {
        return $this->path;
    }
    public function setPath(?string $path): self
    {
        $this->path = $path;

        return $this;
    }
    public function getIsDir(): ?bool
    {
        return $this->isDir;
    }
    public function setIsDir(bool $isDir): self
    {
        $this->isDir = $isDir;

        return $this;
    }
//    public function getLft(): ?int
//    {
//        return $this->lft;
//    }
//    public function setLft(int $lft): self
//    {
//        $this->lft = $lft;
//
//        return $this;
//    }
    public function getLvl(): ?int
    {
        return $this->level;
    }
//    public function setLvl(int $lvl): self
//    {
//        $this->lvl = $lvl;
//
//        return $this;
//    }
//    public function getRoot(): self
//    {
//        return $this->root;
//    }
//    public function setRoot(?File $root): self
//    {
//        $this->root = $root;
//
//        return $this;
//    }
    public function __toString(): string
    {
        return (string) $this->getName();
    }

    public function getExtension(): ?string
    {
        return pathinfo($this->getName(), PATHINFO_EXTENSION);
    }
}

demo/jstree-demo/src/Controller/FileController.php
<?php

namespace App\Controller;

use App\Entity\File;
use App\Repository\FileRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FileController extends AbstractController
{
    #[Route('/file-overview', name: 'app_file_overview')]
    public function index(): Response
    {
        return $this->render('file/index.html.twig', [
            'controller_name' => 'FileController',
        ]);
    }

    #[Route(path: '/repo-files', name: 'app_repo_files')]
    public function files(Request $request, FileRepository $fileRepository)
    {

        // load files dynamically?  Skip repo?
        if (0)
            $htmlTree = $fileRepository->childrenHierarchy(
                null, /* starting from root nodes */
                false, /* false: load all children, true: only direct */
                array(
                    'decorate' => true,
                    'representationField' => 'name',
                    'html' => true,
                    'nodeDecorator' => function ($node)
                    {
                        return sprintf("%s %s %s", $node['name'], $node['code'], $node['lvl']);
                    },
                ),
                true
            );
        return $this->render('file/show.html.twig', [
            'entity' => 'file', // File::class,
            'fileClass' => File::class,
            'entities' => $fileRepository->findBy(['level' => 0]),
            'html' => ''// $htmlTree
        ]);
    }
}

demo/jstree-demo/templates/file/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FileController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/tac/survos/demos/jstree-demo/src/Controller/FileController.php'|file_link(0) }}">src/Controller/FileController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/tac/survos/demos/jstree-demo/templates/file/index.html.twig'|file_link(0) }}">templates/file/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

demo/jstree-demo/templates/file/show.html.twig
{% extends 'layout.html.twig' %}

{#{% set _sc = '@survos/tree-bundle/tree' %}#}

{% block title %}{{ _self}} Demo, uses twig-tree-tag{% endblock %}

{% block body %}
    <span class="bi-alarm"></span>

    <h3>{{ block('title') }}</h3>

    <div class="introduction">
        {{ 'files.intro'|trans }}
        {{ 'files.description'|trans|markdown_to_html }}
    </div>

{#    {% set _sc = 'topic' %}#}
{#    <div {{ stimulus_controller(_sc) }}>#}
{#        <h3 {{ stimulus_target(_sc, 'title') }}>TOPIC title</h3>#}
{#        <div {{ stimulus_target(_sc, 'topic_results') }}>TOPIC results</div>#}
{#    </div>#}

    <div class="row">
        <div class="col-md-3">
            {{ block('tree') }}
        </div>
        <div class="col-md-9">
            {% set _sc = 'file_browser' %}
            <div {{ stimulus_controller(_sc, {
                sourcePath: path('app_file_source')
            }) }}>
                <h3 {{ stimulus_target(_sc, 'title') }}></h3>
                <pre {{ stimulus_target(_sc, 'content') }}>
                    put the file contents here.
                </pre>
            </div>
        </div>
    </div>

    {% endblock %}

{% block tree %}
    <h1>This is a local test of jstree, NOT using the library</h1>
    {% set _sc = 'jstree' %}
    <div
            {{ stimulus_controller(_sc, {

                "types" : {
                    "default" : {
                        "icon" : "bi-alarm"
                    },
                    "php" : {
                        "icon" : "bi bi-filetype-php"
                    },
                    "json" : {
                        "icon" : "bi bi-filetype-json"
                    },
                    "js" : {
                        "icon" : "bi bi-filetype-js"
                    },
                    "yaml" : {
                        "icon" : "bi bi-filetype-yaml"
                    },
                    "css" : {
                        "icon" : "bi bi-filetype-css"
                    },
                    "dir" : {
                        "icon" : "bi bi-arrow-down-right-square"
                    },
                    "demo" : {
                        "icon" : "glyphicon glyphicon-ok"
                    }
                },
                plugins: ['search', 'sort', 'types']
            }) }}
    >

        <input
                {{ stimulus_action(_sc, 'search') }}
                type="text"
                value="" class="input" style="margin:0em auto 1em auto; display:block; padding:4px; border-radius:4px; border:1px solid silver;" />

        <div             {{ stimulus_target(_sc, 'html') }}>

        {% tree e in entities %}
                {% if treeloop.first %}<ul>{% endif %}
                <li
                        data-path="{{ e.path }}"
                        data-type="{{ e.isDir ? 'dir' : 'file' }}"
                        data-jstree='{"path": "{{ e.path }}", "type":"{{ e.isDir ? 'dir' : e.extension }}"}}'>
{#                        {{ treeloop.level }}#}
                        {{ e.name }}
                    <sup>{{ e.isDir ? e.childCount }}</sup>
{#                    <a href="#{{ e.id }}">#}
{#                    </a>#}
                    {% subtree e.children %}
                </li>
                {% if treeloop.last %}</ul>{% endif %}
            {% endtree %}
    </div>

    </div>


{#    {% set _sc = 'jstree' %}#}
{#    <div {{ stimulus_controller(_sc) }}>#}
{#        <div id="html1" class="jstree-basic" {{ stimulus_target(_sc, 'html') }}>#}
{#            {% if html|default(false) %}#}
{#                {{ html|raw }}#}
{#            {% else %}#}
{#                <ul>#}
{#                    <li>Root node 1</li>#}
{#                    <li>Root node 2</li>#}
{#                </ul>#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}


    {{ html|raw }}

{#    <a class="btn btn-danger" href="{{ path('app_load_' ~ entity) }}">Reload {{ entity }}</a>#}

    {% set apiUrl = api_route(fileClass) %}
{#        path('api_%s_get_collection'|format(entity), {_format: 'json'}) %}#}
    Files from this repo (demo), using
    <a target="_blank" href="{{ apiUrl }}">
        {{ apiUrl }}
    </a>


    <div id="file_manager" class="demo"
         data-api-base="{{ apiUrl }}"
    >
        {{ entity }}from this repo (demo), using {{ apiUrl }}

    </div>

{% endblock %}